fix: fixed issue where on some machines (depending on build order) msvc++ would issue `error C4426`
notes: the full error is:
```
17:28:34:936	1>  [4/4] Compile [x64] Module.CkEditorStyle.cpp
17:28:34:936	1>  D:\Repos\CkPlugins\Plugins\CkFoundation\Intermediate\Build\Win64\x64\UnrealEditor\Development\CkEditorStyle\Module.CkEditorStyle.cpp(8): error C4426: optimization flags changed after including header, may be due to #pragma optimize()
17:28:34:936	1>  C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command "D:\Repos\Ck_UnrealEngine\Engine\Build\BatchFiles\Build.bat -Target="CkPluginsEditor Win64 Development -Project=\"D:\Repos\CkPlugins\CkPlugins.uproject\"" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 6.
17:28:34:936	1>Done building target "Build" in project "CkPlugins.vcxproj" -- FAILED.
17:28:34:936	1>
17:28:34:936	1>Done building project "CkPlugins.vcxproj" -- FAILED.
```

Unreal has macros to turn on/off optimizations. These macros have a begin/end and the end should always follow the begin. Depending on how the unity build modules are assembled, a user may or may not get the error if they forget the END counterparts of the macro.